# Generated by Django 4.2.19 on 2025-02-06 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('customer_type', models.CharField(blank=True, choices=[('person', 'person'), ('company', 'company')], max_length=10, null=True)),
                ('pick_point', models.CharField(blank=True, choices=[('onsite', 'onsite'), ('offsite', 'offsite')], max_length=10, null=True)),
                ('appoinment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
