# Generated by Django 4.2.19 on 2025-02-06 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0002_alter_complaint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
