# Generated by Django 4.2.19 on 2025-02-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaintstatuses_components_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='bill_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaint.item'),
        ),
    ]
